<a href="https://colab.research.google.com/github/dn-bit/text_to_vec_using_embedding_layer_technique/blob/main/text_to_vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.12.0


In [1]:
sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [2]:
sent

['The world is a better place',
 'Marvel series is my favourite movie',
 'I like DC movies',
 'the cat is eating the food',
 'Tom and Jerry is my favourite movie',
 'Python is my favourite programming language']

In [3]:
from tensorflow.keras.preprocessing.text import one_hot



In [5]:
voc_size=500

onehot_rep=[one_hot(words,voc_size) for words in sent]
onehot_rep

[[193, 375, 173, 34, 325, 235],
 [461, 309, 173, 17, 423, 128],
 [209, 291, 26, 39],
 [193, 84, 173, 465, 193, 193],
 [237, 88, 406, 173, 17, 423, 128],
 [314, 173, 17, 423, 458, 37]]

In [6]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential

In [7]:
#we alredy converted text into one hot 

#now we need to set sentences in same shape



sent_length=8

embedded_docs=pad_sequences(onehot_rep,padding='pre',maxlen=sent_length)
embedded_docs

array([[  0,   0, 193, 375, 173,  34, 325, 235],
       [  0,   0, 461, 309, 173,  17, 423, 128],
       [  0,   0,   0,   0, 209, 291,  26,  39],
       [  0,   0, 193,  84, 173, 465, 193, 193],
       [  0, 237,  88, 406, 173,  17, 423, 128],
       [  0,   0, 314, 173,  17, 423, 458,  37]], dtype=int32)

In [15]:
#Made model and trained it
dim=10


model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [17]:
embedded_docs[0]

array([  0,   0, 193, 375, 173,  34, 325, 235], dtype=int32)

In [16]:
#predict now

model.predict(embedded_docs[0])

1/1 [==============================] - 0s 155ms/step


array([[ 0.04708885, -0.02492026, -0.03028983, -0.03148373, -0.00224732,
         0.02002772,  0.04525283,  0.03411185, -0.00840392, -0.00200571],
       [ 0.04708885, -0.02492026, -0.03028983, -0.03148373, -0.00224732,
         0.02002772,  0.04525283,  0.03411185, -0.00840392, -0.00200571],
       [-0.02233375, -0.02588486, -0.00923647, -0.0355212 ,  0.01365736,
        -0.00055571,  0.00728353, -0.03773192, -0.01921539,  0.04468362],
       [ 0.01067622, -0.02927796, -0.03736705, -0.04817727,  0.01950485,
        -0.01646971, -0.04659981, -0.04018822,  0.02539608,  0.04256989],
       [ 0.0331023 , -0.00759422, -0.04046335,  0.01807529, -0.02033108,
         0.03315869, -0.00587859, -0.01849655, -0.01024634, -0.00933359],
       [ 0.04206635,  0.01161665, -0.02557957, -0.02850283, -0.04710487,
         0.01796799,  0.00636586,  0.02094731, -0.02378827,  0.00707495],
       [-0.04583374,  0.01837533, -0.0007562 ,  0.01706096, -0.02932318,
        -0.04927009,  0.01398825, -0.02604004

In [18]:
vec=model.predict(embedded_docs)

1/1 [==============================] - 0s 45ms/step


In [19]:
vec

array([[[ 4.70888503e-02, -2.49202605e-02, -3.02898288e-02,
         -3.14837322e-02, -2.24732235e-03,  2.00277232e-02,
          4.52528261e-02,  3.41118462e-02, -8.40391964e-03,
         -2.00570747e-03],
        [ 4.70888503e-02, -2.49202605e-02, -3.02898288e-02,
         -3.14837322e-02, -2.24732235e-03,  2.00277232e-02,
          4.52528261e-02,  3.41118462e-02, -8.40391964e-03,
         -2.00570747e-03],
        [-2.23337542e-02, -2.58848555e-02, -9.23646614e-03,
         -3.55211981e-02,  1.36573575e-02, -5.55705279e-04,
          7.28353113e-03, -3.77319232e-02, -1.92153938e-02,
          4.46836241e-02],
        [ 1.06762163e-02, -2.92779561e-02, -3.73670459e-02,
         -4.81772684e-02,  1.95048489e-02, -1.64697058e-02,
         -4.65998054e-02, -4.01882157e-02,  2.53960826e-02,
          4.25698869e-02],
        [ 3.31023000e-02, -7.59421661e-03, -4.04633507e-02,
          1.80752911e-02, -2.03310847e-02,  3.31586860e-02,
         -5.87859005e-03, -1.84965506e-02, -1.024633